BOT_TOKEN: 
  - ODUyNjI0NDI3MDI3NjYwODUx.G4MpZU.D20d0JhyWDDGrJ6QxQZCRqsBDbZ0CsGmltvG_g
CHANNEL_ID: 
  - 852625097953116211
MODE: quote
REPLY: 
SIMSIMI_LANG: en
DELAY: 20
DEL_AFTER: Y
REPOST_LAST_CHAT: 100